# Custom build setup steps for cargo-dist.
# These steps are injected into the release workflow via the
# github-build-setup option in dist-workspace.toml.
# See: https://opensource.axo.dev/cargo-dist/book/ci/customizing.html

- name: Setup pnpm
  # Installs the pnpm CLI tool
  uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
  with:
    package_json_file: ui/package.json
- name: Setup Node.js
  uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
  with:
    node-version-file: '.nvmrc'
    cache: 'pnpm'
    cache-dependency-path: ui/package-lock.json
- name: Install UI dependencies
  run: pnpm install --frozen-lockfile
  working-directory: ./ui
- name: Build UI
  run: pnpm build
  working-directory: ./ui
