// SPDX-License-Identifier: Apache-2.0

//! Checks that the JSON schemas generated by the current code are backwards-compatible
//! with the schemas published in the latest GitHub release.
//!
//! A removed property path is a breaking change; an added path requires a minor version
//! bump in both `PUBLICATION_MANIFEST_FILE_FORMAT` and `V2_RESOLVED_FILE_FORMAT`.

use anyhow::{bail, Context};
use assert_cmd::Command;
use gix::clone::PrepareFetch;
use gix::create::{self, Kind};
use gix::{open, progress, Repository};
use semver::Version;
use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::fs;
use std::sync::atomic::AtomicBool;

const WEAVER_REPO_URL: &str = "https://github.com/open-telemetry/weaver.git";
const TEMP_REPO_DIR: &str = "schema-compat-temp-repo";

/// (weaver json-schema CLI arg, path in repo, display name)
const CHECKS: &[(&str, &str, &str)] = &[
    (
        "publication-manifest-v2",
        "schemas/publication-manifest.v2.json",
        "PublicationManifestV2",
    ),
    (
        "resolved-registry-v2",
        "schemas/semconv.resolved.v2.json",
        "ResolvedRegistryV2",
    ),
];

#[cfg(not(tarpaulin_include))]
fn fetch_repo() -> anyhow::Result<Repository> {
    let _ = fs::remove_dir_all(TEMP_REPO_DIR);
    let _ = fs::create_dir(TEMP_REPO_DIR);
    let mut fetch = PrepareFetch::new(
        WEAVER_REPO_URL,
        TEMP_REPO_DIR,
        Kind::WithWorktree,
        create::Options {
            destination_must_be_empty: true,
            fs_capabilities: None,
        },
        open::Options::isolated(),
    )?;
    let (repo, _) = fetch.fetch_only(progress::Discard, &AtomicBool::new(false))?;
    Ok(repo)
}

#[cfg(not(tarpaulin_include))]
fn latest_release_tag(repo: &Repository) -> anyhow::Result<String> {
    repo.references()?
        .tags()?
        .filter_map(|r| {
            let r = r.ok()?;
            let tag = r.name().shorten().to_string();
            let ver = Version::parse(tag.trim_start_matches('v')).ok()?;
            Some((ver, tag))
        })
        .max_by_key(|(ver, _)| ver.clone())
        .map(|(_, tag)| tag)
        .context("no release tags found in weaver repo")
}

#[cfg(not(tarpaulin_include))]
fn read_file_at_tag(repo: &Repository, tag: &str, file_path: &str) -> anyhow::Result<String> {
    let reference = repo
        .find_reference(tag)
        .with_context(|| format!("tag {tag} not found"))?;
    let id = reference
        .into_fully_peeled_id()
        .context("failed to peel tag to commit")?;
    let commit = id
        .object()
        .context("failed to get object")?
        .into_commit();
    let tree = commit.tree().context("failed to get tree")?;
    let entry = tree
        .lookup_entry_by_path(file_path)
        .with_context(|| format!("failed to look up {file_path}"))?
        .with_context(|| format!("{file_path} not found at tag {tag}"))?;
    let blob = entry
        .object()
        .context("failed to get blob object")?
        .into_blob();
    String::from_utf8(blob.data.clone())
        .with_context(|| format!("{file_path} is not valid UTF-8"))
}

#[cfg(not(tarpaulin_include))]
fn generate_current(json_schema_arg: &str) -> anyhow::Result<serde_json::Value> {
    let output = Command::cargo_bin("weaver")
        .context("failed to find weaver binary")?
        .args([
            "--quiet",
            "registry",
            "json-schema",
            "--json-schema",
            json_schema_arg,
        ])
        .output()
        .with_context(|| format!("failed to run weaver registry json-schema {json_schema_arg}"))?;

    if !output.status.success() {
        bail!(
            "weaver registry json-schema failed for {json_schema_arg}:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    serde_json::from_slice(&output.stdout)
        .with_context(|| format!("output for {json_schema_arg} is not valid JSON"))
}

/// Recursively collect all property paths from a JSON Schema node.
///
/// Uses dot-notation for nested objects and `[]` suffix for array items.
/// `$ref` pointers are resolved against the top-level `$defs` map; already-visited
/// refs are skipped to prevent infinite loops on recursive schemas.
fn collect_paths(
    node: &serde_json::Value,
    defs: &serde_json::Map<String, serde_json::Value>,
    prefix: &str,
    visited: &mut HashSet<String>,
    paths: &mut BTreeSet<String>,
) {
    if let Some(ref_str) = node.get("$ref").and_then(|v| v.as_str()) {
        let name = ref_str
            .strip_prefix("#/$defs/")
            .unwrap_or(ref_str)
            .to_owned();
        if visited.insert(name.clone()) {
            if let Some(resolved) = defs.get(&name) {
                collect_paths(resolved, defs, prefix, visited, paths);
            }
            visited.remove(&name);
        }
        return;
    }
    for key in &["anyOf", "oneOf", "allOf"] {
        if let Some(arr) = node.get(*key).and_then(|v| v.as_array()) {
            for sub in arr {
                collect_paths(sub, defs, prefix, visited, paths);
            }
        }
    }
    if let Some(props) = node.get("properties").and_then(|v| v.as_object()) {
        for (field, child) in props {
            let path = if prefix.is_empty() {
                field.clone()
            } else {
                format!("{prefix}.{field}")
            };
            paths.insert(path.clone());
            collect_paths(child, defs, &path, visited, paths);
        }
    }
    if let Some(items) = node.get("items") {
        collect_paths(items, defs, &format!("{prefix}[]"), visited, paths);
    }
}

fn schema_paths(schema: &serde_json::Value) -> BTreeSet<String> {
    let defs = schema
        .get("$defs")
        .and_then(|v| v.as_object())
        .cloned()
        .unwrap_or_default();
    let mut paths = BTreeSet::new();
    let mut visited = HashSet::new();
    collect_paths(schema, &defs, "", &mut visited, &mut paths);
    paths
}

/// Read the raw `file_format` const string from a schema, e.g. `"manifest/2.0"`.
fn file_format_const(schema: &serde_json::Value) -> String {
    schema
        .get("properties")
        .and_then(|p| p.get("file_format"))
        .and_then(|f| f.get("const"))
        .and_then(|v| v.as_str())
        .unwrap_or("unknown")
        .to_owned()
}

/// Parse `(major, minor)` from a `file_format` const like `"manifest/2.1"` or `"resolved/2.0"`.
fn schema_version(schema: &serde_json::Value) -> Option<(u64, u64)> {
    let ver_str = schema
        .get("properties")?
        .get("file_format")?
        .get("const")?
        .as_str()?
        .split('/')
        .nth(1)?;
    let mut parts = ver_str.split('.');
    let major: u64 = parts.next()?.parse().ok()?;
    let minor: u64 = parts.next()?.parse().ok()?;
    Some((major, minor))
}

#[cfg(not(tarpaulin_include))]
pub fn run() -> anyhow::Result<()> {
    println!("Fetching weaver repo tags...");
    let repo = fetch_repo().context("failed to fetch weaver repo")?;
    let tag = latest_release_tag(&repo).context("failed to determine latest release tag")?;
    println!("Comparing schemas against {tag}");

    // name → (baseline_format, current_format, removed, added)
    let mut failures: BTreeMap<&str, (String, String, Vec<String>, Vec<String>)> =
        BTreeMap::new();

    for (cli_arg, repo_path, name) in CHECKS {
        print!("  Checking {name} ... ");

        let baseline_text = read_file_at_tag(&repo, &tag, repo_path)
            .with_context(|| format!("failed to read {repo_path} at {tag}"))?;
        let baseline: serde_json::Value = serde_json::from_str(&baseline_text)
            .with_context(|| format!("{repo_path} at {tag} is not valid JSON"))?;

        let current = generate_current(cli_arg)
            .with_context(|| format!("failed to generate current schema for {name}"))?;

        let baseline_fmt = file_format_const(&baseline);
        let current_fmt = file_format_const(&current);
        let current_ver = schema_version(&current).unwrap_or((0, 0));
        // If the baseline predates version tagging in the schema, assume same version
        // as current (conservative: treat all diffs as requiring a version bump).
        let baseline_ver = schema_version(&baseline).unwrap_or(current_ver);

        let baseline_paths = schema_paths(&baseline);
        let current_paths = schema_paths(&current);

        let removed: Vec<String> = baseline_paths
            .difference(&current_paths)
            .filter(|_| current_ver.0 == baseline_ver.0) // same major → breaking
            .cloned()
            .collect();
        let added: Vec<String> = current_paths
            .difference(&baseline_paths)
            .filter(|_| current_ver <= baseline_ver) // minor not bumped → needs bump
            .cloned()
            .collect();

        if removed.is_empty() && added.is_empty() {
            println!("OK");
        } else {
            println!("DIFF");
            failures.insert(name, (baseline_fmt, current_fmt, removed, added));
        }
    }

    let _ = fs::remove_dir_all(TEMP_REPO_DIR);

    if failures.is_empty() {
        return Ok(());
    }

    use std::fmt::Write as _;
    let mut msg = format!(
        "\nSchema compatibility check failed against {tag}.\n\
         To fix: bump the minor version in PUBLICATION_MANIFEST_FILE_FORMAT \
         (weaver_semconv) and V2_RESOLVED_FILE_FORMAT (weaver_resolved_schema) \
         when adding fields, or bump the major version for removals.\n\n"
    );
    for (name, (baseline_fmt, current_fmt, removed, added)) in &failures {
        writeln!(msg, "=== {name} === (baseline: {baseline_fmt}, current: {current_fmt})")?;
        if !removed.is_empty() {
            writeln!(
                msg,
                "  BREAKING — fields removed (backwards-incompatible, consider bumping MAJOR):"
            )?;
            for p in removed {
                writeln!(msg, "    - {p}")?;
            }
        }
        if !added.is_empty() {
            writeln!(msg, "  NEW fields (minor version bump required):")?;
            for p in added {
                writeln!(msg, "    + {p}")?;
            }
        }
    }
    bail!("{msg}");
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn make_schema(file_format_const: &str) -> serde_json::Value {
        json!({
            "properties": {
                "file_format": { "type": "string", "const": file_format_const }
            }
        })
    }

    #[test]
    fn test_schema_version_parses() {
        assert_eq!(schema_version(&make_schema("manifest/2.0")), Some((2, 0)));
        assert_eq!(schema_version(&make_schema("manifest/2.0.0")), Some((2, 0)));
        assert_eq!(schema_version(&make_schema("resolved/2.1")), Some((2, 1)));
        assert_eq!(schema_version(&json!({})), None);
        // When baseline lacks version info, unwrap_or(current_ver) makes them equal,
        // so added fields are still flagged (conservative fallback).
        let current_ver = schema_version(&make_schema("manifest/2.0")).unwrap_or((0, 0));
        let baseline_ver = schema_version(&json!({})).unwrap_or(current_ver);
        assert_eq!(baseline_ver, current_ver);
    }

    #[test]
    fn test_collect_paths_basic() {
        let schema = json!({
            "properties": {
                "name": { "type": "string" },
                "items": {
                    "type": "array",
                    "items": { "properties": { "id": { "type": "string" } } }
                }
            }
        });
        let paths = schema_paths(&schema);
        assert!(paths.contains("name"));
        assert!(paths.contains("items"));
        assert!(paths.contains("items[].id"));
    }

    #[test]
    fn test_collect_paths_ref() {
        let schema = json!({
            "$defs": {
                "Child": { "properties": { "x": { "type": "string" } } }
            },
            "properties": {
                "child": { "$ref": "#/$defs/Child" }
            }
        });
        let paths = schema_paths(&schema);
        assert!(paths.contains("child"));
        assert!(paths.contains("child.x"));
    }
}
