// SPDX-License-Identifier: Apache-2.0

//! Finding ID enum for live check findings.
//!
//! DO NOT EDIT — this file is generated by Weaver from `model/live_check.yaml`.
//! To regenerate, run from the repository root:
//!
//! ```sh
//! cargo run -- registry generate \
//!   --registry crates/weaver_live_check/model/ \
//!   --templates crates/weaver_live_check/templates/ \
//!   --v2 \
//!   rust \
//!   crates/weaver_live_check/src/
//! ```

use serde::{Deserialize, Serialize};

/// Unique identifier for the type of finding detected by the policy engine
///
/// The finding ID is a stable, machine-readable identifier that categorizes the issue.
/// It can be used to filter, aggregate, or suppress specific finding types.
///
/// IDs prefixed with common patterns indicate the source: built-in advisors produce
/// findings like `missing_attribute` and `type_mismatch`, requirement-level checks
/// produce `*_attribute_not_present` findings, and Rego policies produce findings
/// like `missing_namespace` and `invalid_format`.
///
/// Custom Rego policies may emit additional finding IDs not listed here.
///
/// The `Custom` variant represents finding IDs from custom Rego policies
/// or other external sources not listed above.
#[derive(
    Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize, strum::Display, strum::EnumString,
)]
#[serde(rename_all = "snake_case")]
#[strum(serialize_all = "snake_case")]
pub enum FindingId {
    /// An attribute is not defined in the semantic convention registry
    MissingAttribute,
    /// An attribute matched a template definition in the registry
    TemplateAttribute,
    /// A metric is not defined in the semantic convention registry
    MissingMetric,
    /// An event is not defined in the semantic convention registry
    MissingEvent,
    /// A deprecated attribute or signal is in use
    Deprecated,
    /// An attribute value type does not match the type defined in the registry
    TypeMismatch,
    /// An attribute or signal has not reached stable status
    NotStable,
    /// A metric unit does not match the unit defined in the registry
    UnitMismatch,
    /// A metric instrument type does not match or is not supported by the registry
    UnexpectedInstrument,
    /// An enum attribute value is not in the set of allowed members
    UndefinedEnumVariant,
    /// A required attribute is absent from the sample
    RequiredAttributeNotPresent,
    /// A recommended attribute is absent from the sample
    RecommendedAttributeNotPresent,
    /// An opt-in attribute is absent from the sample
    OptInAttributeNotPresent,
    /// A conditionally required attribute is absent from the sample
    ConditionallyRequiredAttributeNotPresent,
    /// An attribute name has no dot-separated namespace
    MissingNamespace,
    /// An attribute or metric name does not match the required naming format
    InvalidFormat,
    /// An attribute name uses a namespace that collides with an existing attribute
    IllegalNamespace,
    /// An attribute name shares a namespace prefix with existing registry attributes
    ExtendsNamespace,
    /// A finding ID from a custom Rego policy or other external source
    #[serde(untagged)]
    #[strum(default)]
    Custom(String),
}

impl From<FindingId> for String {
    fn from(id: FindingId) -> Self {
        id.to_string()
    }
}
