# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# This is used with cargo-check-external-types to reduce the surface area of downstream crates from
# the public API. Ideally this can have a few exceptions as possible.
allowed_external_types = [
    "weaver_semconv::Error",
    "weaver_common::*",
    "weaver_forge::error::Error",
    "miette::protocol::Diagnostic",
    "serde_core::ser::Serialize",
    "weaver_resolved_schema::v2::ResolvedTelemetrySchema",
    "weaver_forge::v2::registry::ForgeResolvedRegistry",
    "weaver_forge::output_processor::OutputProcessor",
    "weaver_resolved_schema::ResolvedTelemetrySchema",
    "weaver_semconv::registry_repo::RegistryRepo",
    "weaver_resolver::error::Error",
]
