{{- template.set_file_name("lib.rs") -}}

/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

//! OpenTelemetry Semantic Convention Attributes.
//! DO NOT EDIT, THIS FILE HAS BEEN GENERATED BY WEAVER

pub mod attributes;
pub mod metrics;

